#!/bin/bash
#author by Firzii

clear
blue='\033[31;1m'
red='\033[32;1m'
white='\033[33;1m'
purple='\033[34;1m'
yellow='\033[35;1m'
cyan='\033[36;1m'

echo -e $blue"======================================================="
echo -e $yellow"==             Name:Firzii                         =="
echo -e $yellow"==             Nick:Mr.HurT3d                      =="
echo -e $yellow"==             Team:Indonesian Sad Cyber           =="
echo -e $blue"======================================================="   
echo -e $red"Tools Buatan Gua Sendiri Hehe"
echo -e $white"daftar toolsnya=>"
echo -e $cyan"[1] Tools Spam Wa (spam chat)"
echo -e $cyan"[2] Tools Spam Wa (spam telepon)"
echo -e $cyan"[3] Tools Gps-Tracking"
echo
echo -e $yellow
read -p"rootlocalhost@Firzii=$" zii;

if [ $zii = 1 ] || [ $zii = 1]
then
clear
echo -e $green"Spam Wa Chat"
sleep 1
pkg update && pkg upgrade
pkg install git -y
pkg install php -y
git clone https://github.com/hurted/WaSpam
cd WaSpam
php chat.php
fi

if [ $zii = 2 ] || [ $zii = 2 ]
then
clear
echo -e $red"Spam Wa Telepon"
pkg update && pkg upgrade
pkg insall git -y
pkg instll php -y
git clone https://github.com/hurted/WaSpam
cd WaSpam
php call.php
if

if [ $zii = 3 ] || [ $zii = 3 ]
then
clear
echo -e $blue"Tools Cyduk Orang hehe"
sleep 1
pkg update && pkg upgrade
pkg install git -y
pkg install php -y
git clone https://github.com/hurted/gps-tracking
cd gps-tracking
php gps.php
fi
exit
