#!/bin/bash
#author by Firzii

clear
blue='\033[31;1m'
red='\033[32;1m'
white='\033[33;1m'
purple='\033[34;1m'
yellow='\033[35;1m'
cyan='\033[36;1m'

figlet FirziiU | lolcat
echo -e $red"Tools Buatan Gua Sendiri Hehe"
echo -e $white"daftar toolsnya=>"
echo -e $cyan"[1] Tools Spam Wa Firzii"
echo -e $cyan"[2] Tools Gps-Tracking"
echo
echo -e $yellow
read -p"rootlocalhost@Firzii=$" zii;

if [ $zii = 1 ] || [ $zii = 1]
then
clear
echo -e $green"Tools Spam Wa"
sleep 1
pkg update && pkg upgrade
pkg install git -y
pkg install php -y
git clone https://github.com/hurted/SpamWa
cd SpamWa
php chat.php
fi

if [ $zii = 2 ] || [ $zii = 2]
then
clear
echo -e $blue"Tools Cyduk Orang hehe"
sleep 1
pkg update && pkg upgrade
pkg install git -y
pkg install php -y
git clone https://github.com/hurted/gps-tracking
cd gps-tracking
php gps.php
fi
exit
